name: pg-install-ci-check

on: push

permissions:
  contents: read

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [
            # "2.1", # Disabled because rails (~> 5.1.0) only support ruby (>= 2.2.2)
            # "2.2", # Disabled because ruby/setup-ruby doesn't work.
            "2.3",
            "2.4",
            "2.5",
            "2.6",
            "2.7",
            "3.0",
            "3.1",
            "3.2",
            "3.3",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: pg install
        run: MAKEFLAGS=V=1 gem install --verbose pg -v '~> 0.11'
      - name: Run tests
        run: bundle exec rake
  test-macos-latest:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [
            # "2.1", # Disabled because rails (~> 5.1.0) only support ruby (>= 2.2.2)
            # "2.2", # Disabled because ruby/setup-ruby doesn't work.
            "2.3",
            "2.4",
            "2.5",
            "2.6",
            "2.7",
            "3.0",
            "3.1",
            "3.2",
            "3.3",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: pg install
        run: MAKEFLAGS=V=1 gem install --verbose pg -v '~> 0.11'
      - name: Run tests
        run: bundle exec rake
